FROM node:22-alpine AS builder
WORKDIR /app
COPY FrontendProyectoPQR/package*.json ./
RUN npm ci
COPY FrontendProyectoPQR/ .
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=builder /app/dist/pqrs-frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
