# Perfil de producción para despliegue con Docker + PostgreSQL

spring.datasource.url=jdbc:postgresql://db:5432/pqrsdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=pqrsuser
spring.datasource.password=pqrspass
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=false

app.security.jwt.secret=${APP_SECURITY_JWT_SECRET}

logging.level.co.edu.uniquindio=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.core=INFO
