spring.application.name=proyecto

# Debug logging
logging.level.co.edu.uniquindio=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.core=DEBUG
logging.level.springdoc=DEBUG
logging.level.io.swagger.v3=DEBUG
logging.level.com.fasterxml.jackson=DEBUG
